services:
  - type: web
    name: Device Panel Backend
    env: node
    buildCommand: 'npm install'
    startCommand: 'npm start'
    plan: free
    envVars:
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_password
      - key: DB_HOST
        value: your_db_host
      - key: DB_PORT
        value: 3306
